default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] || localhost %>
  port: <%= ENV["DB_PORT"] || 5432 %>
  username: <%= ENV["DB_USERNAME"] || postgres %>
  password: <%= ENV["DB_PASSWORD"] || postgres %>
  # DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chat_app_development

test:
  <<: *default
  database: chat_app_test

production:
  <<: *default
  database: chat_app_production
